version: "3.3"
services:
  webapp:
    image: image1
    ports:
      - 85:80
    deploy:
      replicas: 2
services:
  loginapp:
    image: image2
    ports:
      - 81:80
    deploy:
      replicas: 2
